/**
 * QR Code Utilities for Registration Check-in
 *
 * Pure logic for:
 * - Building QR code payload URLs from registration tokens
 * - Parsing QR payloads back to tokens
 * - Validating QR token format
 * - Determining check-in eligibility from registration status
 *
 * All functions are DB-free for unit testing.
 */

// ── Types ────────────────────────────────────────────────────

export type QrPayload = {
  token: string;
  eventId: string;
};

export type QrParseResult =
  | { valid: true; token: string; eventId: string }
  | { valid: false; error: string };

export type CheckInEligibility = {
  eligible: boolean;
  reason?: string;
};

// ── Constants ────────────────────────────────────────────────

/** QR tokens are 32-char alphanumeric strings generated by generateQrToken() */
const QR_TOKEN_PATTERN = /^[A-Za-z0-9]{32}$/;
const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Path prefix for QR check-in URLs */
export const QR_CHECKIN_PATH = '/checkin';

function normalizeRequiredString(value: string, fieldName: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(`${fieldName} is required`);
  }

  return value.trim();
}

// ── QR Payload Building ──────────────────────────────────────

/**
 * Build the full URL that gets encoded into a QR code.
 * Format: {baseUrl}/checkin?token={qrCodeToken}&event={eventId}
 */
export function buildQrPayloadUrl(
  baseUrl: string,
  token: string,
  eventId: string,
): string {
  const normalizedBaseUrl = normalizeRequiredString(baseUrl, 'baseUrl');
  const normalizedToken = normalizeRequiredString(token, 'token');
  const normalizedEventId = normalizeRequiredString(eventId, 'eventId');

  if (!QR_TOKEN_PATTERN.test(normalizedToken)) {
    throw new Error('token format is invalid');
  }

  if (!UUID_PATTERN.test(normalizedEventId)) {
    throw new Error('eventId format is invalid');
  }

  const parsedBaseUrl = new URL(normalizedBaseUrl);
  if (!['http:', 'https:'].includes(parsedBaseUrl.protocol)) {
    throw new Error('baseUrl must use http or https');
  }

  const url = new URL(QR_CHECKIN_PATH, parsedBaseUrl);
  url.searchParams.set('token', normalizedToken);
  url.searchParams.set('event', normalizedEventId);
  return url.toString();
}

/**
 * Build just the token-only payload for compact QR codes.
 * Used when the scanner app already knows the event context.
 */
export function buildCompactQrPayload(token: string, eventId: string): string {
  const normalizedToken = normalizeRequiredString(token, 'token');
  const normalizedEventId = normalizeRequiredString(eventId, 'eventId');

  if (!QR_TOKEN_PATTERN.test(normalizedToken)) {
    throw new Error('token format is invalid');
  }

  if (!UUID_PATTERN.test(normalizedEventId)) {
    throw new Error('eventId format is invalid');
  }

  return `${normalizedEventId}:${normalizedToken}`;
}

// ── QR Payload Parsing ───────────────────────────────────────

/**
 * Parse a QR payload URL back into its components.
 * Handles both full URLs and compact payloads.
 */
export function parseQrPayload(payload: string): QrParseResult {
  if (!payload || typeof payload !== 'string') {
    return { valid: false, error: 'Empty or invalid payload' };
  }

  const trimmed = payload.trim();

  // Try compact format first: {eventId}:{token}
  const compactMatch = trimmed.match(
    /^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}):([A-Za-z0-9]{32})$/i,
  );
  if (compactMatch) {
    return { valid: true, eventId: compactMatch[1], token: compactMatch[2] };
  }

  // Try full URL format
  try {
    const url = new URL(trimmed);

    if (!['http:', 'https:'].includes(url.protocol) || url.pathname !== QR_CHECKIN_PATH) {
      return { valid: false, error: 'Invalid QR payload URL' };
    }

    const token = url.searchParams.get('token');
    const eventId = url.searchParams.get('event');

    if (!token || !eventId) {
      return { valid: false, error: 'Missing token or event parameter' };
    }

    if (!QR_TOKEN_PATTERN.test(token)) {
      return { valid: false, error: 'Invalid token format' };
    }

    if (!UUID_PATTERN.test(eventId)) {
      return { valid: false, error: 'Invalid event ID format' };
    }

    return { valid: true, token, eventId };
  } catch {
    return { valid: false, error: 'Unrecognized QR format' };
  }
}

// ── Token Validation ─────────────────────────────────────────

/**
 * Validate that a string matches the expected QR token format.
 */
export function isValidQrToken(token: string): boolean {
  return typeof token === 'string' && QR_TOKEN_PATTERN.test(token);
}

// ── Check-in Eligibility ─────────────────────────────────────

/** Registration statuses that allow check-in */
const CHECKIN_ELIGIBLE_STATUSES = new Set(['confirmed']);

/**
 * Determine if a registration is eligible for check-in based on its status.
 * Only confirmed registrations can be checked in.
 */
export function checkRegistrationEligibility(
  registrationStatus: string,
  registrationCancelledAt: Date | null,
): CheckInEligibility {
  if (registrationCancelledAt) {
    return { eligible: false, reason: 'Registration has been cancelled' };
  }

  if (!CHECKIN_ELIGIBLE_STATUSES.has(registrationStatus)) {
    return {
      eligible: false,
      reason: `Registration status "${registrationStatus}" is not eligible for check-in. Only confirmed registrations can be checked in.`,
    };
  }

  return { eligible: true };
}

/**
 * Determine the scan result type based on lookup outcome.
 */
export type ScanResultType = 'success' | 'duplicate' | 'invalid' | 'ineligible';

export type ScanLookupResult = {
  type: ScanResultType;
  message: string;
  personName?: string;
  registrationNumber?: string;
  category?: string;
};

export function determineScanResult(params: {
  tokenFound: boolean;
  registration?: {
    status: string;
    cancelledAt: Date | null;
    personName: string;
    registrationNumber: string;
    category: string;
  };
  alreadyCheckedIn: boolean;
  sessionId?: string | null;
}): ScanLookupResult {
  const { tokenFound, registration, alreadyCheckedIn, sessionId } = params;

  if (!tokenFound || !registration) {
    return { type: 'invalid', message: 'QR code not recognized. No matching registration found.' };
  }

  const eligibility = checkRegistrationEligibility(
    registration.status,
    registration.cancelledAt,
  );

  if (!eligibility.eligible) {
    return {
      type: 'ineligible',
      message: eligibility.reason!,
      personName: registration.personName,
      registrationNumber: registration.registrationNumber,
      category: registration.category,
    };
  }

  if (alreadyCheckedIn) {
    const scope = sessionId ? 'this session' : 'this event';
    return {
      type: 'duplicate',
      message: `Already checked in for ${scope}.`,
      personName: registration.personName,
      registrationNumber: registration.registrationNumber,
      category: registration.category,
    };
  }

  return {
    type: 'success',
    message: 'Check-in successful!',
    personName: registration.personName,
    registrationNumber: registration.registrationNumber,
    category: registration.category,
  };
}
